import { Assessment } from './types';

export const mockAssessments: Assessment[] = [
    {
        id: 1,
        title: 'Frontend Developer Test',
        company: 'Adobe Creative Team',
        status: 'Available',
        date: 'June 15, 2023',
        time: 'June 15, 2023 10:00 AM EST',
        logo: '/logos/adobe.png',
    },
    {
        id: 2,
        title: 'React Coding Challenge',
        company: 'Facebook Engineers',
        status: 'In Progress',
        date: 'June 18, 2023',
        time: 'June 18, 2023 1:00 PM EST',
        logo: '/logos/facebook.png',
    },
    {
        id: 3,
        title: 'Cloud Architecture Quiz',
        company: 'Amazon AWS Team',
        status: 'Completed',
        date: 'June 10, 2023',
        time: 'June 10, 2023 11:00 AM EST',
        score: 85,
        logo: '/logos/amazon.png',
        posted: false,
    },
    {
        id: 4,
        title: 'Machine Learning Basics',
        company: 'Google AI Team',
        status: 'Available',
        date: 'June 5, 2023',
        time: 'June 5, 2023 2:00 PM EST',
        logo: '/logos/google.png',
    },
    {
        id: 5,
        title: 'UI/UX Design Assessment',
        company: 'Airbnb Design Team',
        status: 'Completed',
        date: 'June 3, 2023',
        time: 'June 3, 2023 3:00 PM EST',
        score: 92,
        logo: '/logos/airbnb.png',
        posted: false,
    },
    {
        id: 6,
        title: 'iOS Development Test',
        company: 'Apple Developer Team',
        status: 'In Progress',
        date: 'June 20, 2023',
        time: 'June 20, 2023 1:00 PM EST',
        logo: '/logos/apple.png',
    },
    {
        id: 7,
        title: 'Azure Security Exam',
        company: 'Microsoft Azure Team',
        status: 'Available',
        date: 'June 12, 2023',
        time: 'June 12, 2023 10:00 AM EST',
        logo: '/logos/microsoft.png',
    },
    {
        id: 8,
        title: 'Microservices Evaluation',
        company: 'Netflix Engineering',
        status: 'Completed',
        date: 'June 25, 2023',
        time: 'June 25, 2023 9:00 AM EST',
        score: 78,
        logo: '/logos/netflix.png',
        posted: false,
    },
]; 